import type { Language } from "./types";

// Kinyarwanda strings must be reviewed by a native speaker before the demo.
export const strings = {
  rw: {
    brand: "Umujyanama w'Ubuhinzi",
    brandSub: "SAN TECH",
    newChat: "Ikiganiro gishya",
    history: "Ibiganiro byawe",
    historyEmpty: "Nta kiganiro kirabikwa. Baza ikibazo cya mbere!",
    deleteChat: "Siba iki kiganiro",
    openMenu: "Fungura urutonde",
    closeMenu: "Funga urutonde",
    online: "Iri ku murongo",
    channelsTitle: "Nta interineti?",
    channelsUssd: "Kanda {code} kuri telefoni iyo ari yo yose",
    channelsSms: "Igisubizo kiza kuri SMS",
    footerNote: "Inama zishingiye ku nyandiko za RAB, MINAGRI na FAO. Niba utizeye, baza agronome w'umurenge.",
    welcomeTitle: "Muraho! Ndi umujyanama wawe w'ubuhinzi.",
    welcomeText: "Mbaza ku bigori, ibishyimbo n'ibirayi: gutera, ifumbire, indwara n'ibyonnyi, kubika umusaruro n'ibindi.",
    capType: "Andika",
    capSpeak: "Vuga",
    capPhoto: "Ohereza ifoto",
    capUssd: "USSD",
    tryThese: "Hitamo ikibazo cyo gutangiriraho",
    crop_maize: "Ibigori",
    crop_beans: "Ibishyimbo",
    crop_potato: "Ibirayi",
    placeholder: "Andika ikibazo cyawe…",
    send: "Ohereza",
    sources: "Aho amakuru yavuye",
    error: "Igisubizo nticyabonetse. Reba ko seriveri ikora, hanyuma wongere ugerageze.",
    crop: "Igihingwa",
    topic: "Ingingo",
    time: "Igihe",
    you: "Wowe",
    advisor: "Umujyanama",
    stepRead: "Turimo gusoma ikibazo cyawe…",
    stepSearch: "Turashaka amakuru mu nyandiko z'ubuhinzi…",
    stepWrite: "Turimo gutegura igisubizo…",
    stepSlow: "Biracyakorwa, mwihangane gato…",
    stepPhoto: "Turimo gusuzuma ifoto…",
    addPhoto: "Ongeraho ifoto y'igihingwa",
    removePhoto: "Kuraho ifoto",
    photoOnly: "Ifoto y'igihingwa",
    photoTooBig: "Ifoto irarenze 6 MB. Hitamo indi ntoya.",
    photoFinding: "Ifoto yerekana",
    confidence: "Icyizere",
    conf_high: "kinini",
    conf_medium: "giciriritse",
    conf_low: "gito",
    micStart: "Vuga ikibazo cyawe",
    micStop: "Hagarika gufata amajwi",
    micListening: "Ndakumva… kanda kugira ngo uhagarike",
    micTranscribing: "Turimo kwandika ibyo wavuze…",
    micCheck: "Reba niba byanditswe neza, ukosore niba ari ngombwa, hanyuma wohereze.",
    micDenied: "Mikoro ntiyemewe. Emerera urubuga gukoresha mikoro.",
    micFailed: "Ntitwabashije kumva neza. Ongera ugerageze cyangwa wandike ikibazo.",
    listen: "Umva igisubizo",
    stopListening: "Hagarika",
    preparingAudio: "Turimo gutegura amajwi…",
    audioFailed: "Amajwi ntabonetse, ongera ugerageze",
    photoNotKept: "(ifoto ntiyabitswe)",
    developedBy: "Byakozwe na",
  },
  en: {
    brand: "Farm Advisor",
    brandSub: "SAN TECH",
    newChat: "New conversation",
    history: "Your conversations",
    historyEmpty: "No saved conversations yet. Ask your first question!",
    deleteChat: "Delete this conversation",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    online: "Online",
    channelsTitle: "No internet?",
    channelsUssd: "Dial {code} on any phone",
    channelsSms: "The answer comes by SMS",
    footerNote: "Advice based on RAB, MINAGRI and FAO guidance. If unsure, ask your sector agronomist.",
    welcomeTitle: "Hello! I am your farming advisor.",
    welcomeText: "Ask me about maize, beans and Irish potatoes: planting, fertilizer, pests and diseases, storage and more.",
    capType: "Type",
    capSpeak: "Speak",
    capPhoto: "Send a photo",
    capUssd: "USSD",
    tryThese: "Pick a question to start",
    crop_maize: "Maize",
    crop_beans: "Beans",
    crop_potato: "Irish potatoes",
    placeholder: "Type your question…",
    send: "Send",
    sources: "Sources",
    error: "No answer received. Check that the backend is running, then try again.",
    crop: "Crop",
    topic: "Topic",
    time: "Time",
    you: "You",
    advisor: "Advisor",
    stepRead: "Reading your question…",
    stepSearch: "Searching farming guides…",
    stepWrite: "Writing your answer…",
    stepSlow: "Still working, please wait a little…",
    stepPhoto: "Checking your photo…",
    addPhoto: "Add a photo of the plant",
    removePhoto: "Remove photo",
    photoOnly: "Photo of the plant",
    photoTooBig: "The photo is larger than 6 MB. Choose a smaller one.",
    photoFinding: "Photo shows",
    confidence: "Confidence",
    conf_high: "high",
    conf_medium: "medium",
    conf_low: "low",
    micStart: "Speak your question",
    micStop: "Stop recording",
    micListening: "Listening… tap to stop",
    micTranscribing: "Writing down what you said…",
    micCheck: "Check the text, correct it if needed, then send.",
    micDenied: "Microphone not allowed. Allow this site to use the microphone.",
    micFailed: "We could not hear clearly. Try again or type your question.",
    listen: "Listen to the answer",
    stopListening: "Stop",
    preparingAudio: "Preparing audio…",
    audioFailed: "Audio not available, try again",
    photoNotKept: "(photo not saved)",
    developedBy: "Developed by",
  },
} satisfies Record<Language, Record<string, string>>;

export type Strings = (typeof strings)["rw"];

export const USSD_CODE = "*384*74619#";

export type Crop = "maize" | "beans" | "potato";

export const starterQuestions: Record<Language, Record<Crop, string[]>> = {
  rw: {
    maize: [
      "Amababi y'ibigori byanjye afite imyobo. Ni iki kandi nakora iki?",
      "Nabika nte ibigori kugira ngo bitabora cyangwa ngo bifatwe n'imungu?",
    ],
    beans: [
      "Ni ryari nkwiye kubagara ibishyimbo byanjye?",
      "Ubutaka bwanjye burasharira, ibishyimbo ntibikura neza. Nakora iki?",
    ],
    potato: [
      "Nakoresha ifumbire ingana iki ku birayi mu murima wanjye muto?",
      "Amababi y'ibirayi byanjye afite ibibara by'ikigina nyuma y'imvura. Nakora iki?",
    ],
  },
  en: {
    maize: [
      "My maize leaves have holes. What is it and what should I do?",
      "How do I store maize so it does not rot or get weevils?",
    ],
    beans: [
      "When should I weed my beans?",
      "My soil is acidic and my beans grow poorly. What should I do?",
    ],
    potato: [
      "How much fertilizer should I use for Irish potatoes on my small plot?",
      "My potato leaves have brown patches after rain. What should I do?",
    ],
  },
};
